const c = document.getElementById('game');
const x = c.getContext('2d');
let W=0,H=0,dpr=1;
const houses=[{x:120,y:220,w:120,h:90,b:'#d98a5f',r:'#9f4f2e',d:'#4d2c1f'},{x:360,y:220,w:120,h:90,b:'#6bb6d8',r:'#3e6f92',d:'#2d3c4a'},{x:600,y:220,w:120,h:90,b:'#b26bdd',r:'#6e3e99',d:'#4b2c61'}];
const npc={x:320,y:430,name:'Mina',line:'Hey, click me.'};
const p={x:80,y:430,r:18,s:2.8};
let keys={},state='town',house=-1;
function rs(){dpr=Math.min(window.devicePixelRatio||1,2);W=c.width=Math.floor(innerWidth*dpr);H=c.height=Math.floor(innerHeight*dpr);c.style.width='100vw';c.style.height='100vh';}
function rect(a,b,w,h,c0){x.fillStyle=c0;x.fillRect(a,b,w,h)}
function drawPlayer(px,py){rect(px-14,py-34,28,34,'#2f66ff');x.fillStyle='#ffd2a1';x.beginPath();x.arc(px,py-48,16,0,Math.PI*2);x.fill();rect(px-10,py,8,18,'#222');rect(px+2,py,8,18,'#222')}
function drawNpc(px,py){rect(px-12,py-30,24,30,'#7f5a44');x.fillStyle='#f0c48a';x.beginPath();x.arc(px,py-42,14,0,Math.PI*2);x.fill();rect(px-8,py,6,16,'#3b2a20');rect(px+2,py,6,16,'#3b2a20')}
function door(h){return {x:h.x+h.w/2-10,y:h.y+h.h-24,w:20,h:24}}
function inDoor(){return houses.findIndex(h=>p.x>door(h).x&&p.x<door(h).x+door(h).w&&p.y>door(h).y&&p.y<door(h).y+door(h).h)}
function chat(){let d=document.getElementById('d');if(!d){d=document.createElement('div');d.id='d';d.style='position:fixed;left:50%;bottom:20px;transform:translateX(-50%);background:#fff;border:3px solid #000;border-radius:12px;padding:12px;font:700 16px system-ui;z-index:9';document.body.appendChild(d);}d.innerHTML='<div>Mina: Hey, click me.</div><div style="margin-top:8px;display:flex;gap:8px;flex-wrap:wrap"><button id=a>Hi</button><button id=b>Bye</button></div>';setTimeout(()=>{const a=document.getElementById('a'),b=document.getElementById('b');if(a)a.onclick=()=>{d.firstChild.textContent='You: Hi';setTimeout(()=>d.remove(),700)};if(b)b.onclick=()=>{d.firstChild.textContent='You: Bye';setTimeout(()=>d.remove(),700)}},0)}
function step(){let dx=0,dy=0;if(keys.KeyA||keys.ArrowLeft)dx--;if(keys.KeyD||keys.ArrowRight)dx++;if(keys.KeyW||keys.ArrowUp)dy--;if(keys.KeyS||keys.ArrowDown)dy++;const l=Math.hypot(dx,dy)||1;p.x+=dx/l*p.s;p.y+=dy/l*p.s;p.x=Math.max(20,Math.min(W-20,p.x));p.y=Math.max(20,Math.min(H-20,p.y));}
function drawTown(){x.fillStyle='#87c7ff';x.fillRect(0,0,W,H);x.fillStyle='#87c26b';x.fillRect(0,H*0.45,W,H*0.55);x.fillStyle='#d9c39b';x.fillRect(0,H*0.42,W,10);x.fillStyle='#ff0';x.fillRect(0,0,30*dpr,30*dpr);houses.forEach(h=>{rect(h.x,h.y,h.w,h.h,h.b);x.fillStyle=h.r;x.beginPath();x.moveTo(h.x-12,h.y+4);x.lineTo(h.x+h.w/2,h.y-30);x.lineTo(h.x+h.w+12,h.y+4);x.closePath();x.fill();const d=door(h);rect(d.x,d.y,d.w,d.h,h.d);rect(h.x+18,h.y+18,18,18,'#f7f4dc');rect(h.x+h.w-36,h.y+18,18,18,'#f7f4dc')});drawNpc(npc.x,npc.y);drawPlayer(p.x,p.y);x.fillStyle='#000';x.font=`${18*dpr}px sans-serif`;x.fillText('MorganLife',20,28);x.fillText('Town view',20,52)}
function drawHouse(){const h=houses[house];x.fillStyle='#87c7ff';x.fillRect(0,0,W,H);x.fillStyle='#ff0';x.fillRect(0,0,30*dpr,30*dpr);x.fillStyle='#d9edf9';x.fillRect(0,H*0.62,W,H*0.38);rect(W*0.16,H*0.56,W*0.28,H*0.12,'#b07b6a');rect(W*0.46,H*0.48,W*0.22,H*0.18,'#f0e1c1');rect(W*0.70,H*0.28,W*0.10,H*0.12,'#5b73d4');x.fillStyle='#ffe07b';x.beginPath();x.arc(W*0.76,H*0.24,26*dpr,0,Math.PI*2);x.fill();rect(W*0.53,H*0.68,W*0.14,H*0.06,'#6a4b3a');drawPlayer(p.x,p.y);x.fillStyle='#000';x.fillText('Inside '+h.label,20,52)}
function loop(){rs();step();if(state==='town')drawTown();else drawHouse();x.fillStyle='rgba(0,0,0,.75)';x.fillRect(10,H-54,620,44);x.fillStyle='#fff';x.font=`${14*dpr}px system-ui`;x.fillText(state==='town'?'Walk into a door to enter. Click the NPC to talk.':'Walk back to the door to leave.',18,H-28);requestAnimationFrame(loop)}
c.addEventListener('click',e=>{if(state==='town'){const sx=e.clientX*dpr,sy=e.clientY*dpr;const nx=npc.x*dpr,ny=npc.y*dpr;if(Math.hypot(sx-nx,sy-ny)<60*dpr){chat();return}const i=inDoor();if(i>=0){state='house';house=i;p.x=houses[i].x+houses[i].w/2;p.y=houses[i].y+houses[i].h+10;return}}else{const h=houses[house],d=door(h);if(p.x>d.x&&p.x<d.x+d.w&&p.y>d.y&&p.y<d.y+d.h){state='town';p.x=80;p.y=430}}});addEventListener('keydown',e=>keys[e.code]=true);addEventListener('keyup',e=>keys[e.code]=false);addEventListener('resize',rs);rs();loop();
